/* eslint-disable */
// Auto‑generated by MCP from Supabase
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "13.0.4"
  }
  public: {
    Tables: {
      /* ... truncated for brevity, see MCP output for full content ... */
    }
    Views: { [_ in never]: never }
    Functions: { jwt_org_id: { Args: Record<PropertyKey, never>; Returns: string } }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}
